blueprint:
  name: Motion-activated entity
  description: Turn on a light, switch, scene, script or group when motion is detected.
  domain: automation
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion

    lightsensor_entity:
      name: Illuminance Sensor
      selector:
        entity:
          domain: sensor
          device_class: illuminance

    illuminace_level:
      name: Max Illuminance 
      description: Max immuminance (brightness) level. If illuminance is higher, then the target entity will not be turned on.
      default: 30
      selector:
        number:
          min: 0.0
          max: 300.0
          unit_of_measurement: lux
          mode: slider
          step: 1.0

    target_entity:
      name: Target entity
      description: The light, switch, scene to turn on (or script to run) when the automation is triggered.
      selector:
        entity:

    schedule_start:
      name: Schedule start time
      description: Automation only runs after this time.
      default: '07:00:00'
      selector:
        time:

    schedule_stop:
      name: Schedule stop time
      description: Automation does not run after this time.
      default: '23:59:00'
      selector:
        time:

    idle_time:
      name: Motion idle time
      description: Time to leave the light on after the last motion is detected.
      default: 2
      selector:
        number:
          min: 0.0
          max: 60.0
          unit_of_measurement: minutes
          mode: slider
          step: 1.0
  source_url: https://github.com/jturn08/smarthome/blob/main/esphome/blueprints/turn-on-entity-with-motion.yaml
mode: restart
max_exceeded: silent

trigger:
- platform: state
  entity_id: !input 'motion_entity'
  from: 'off'
  to: 'on'

condition:
- condition: and
  conditions:
  - condition: numeric_state
    entity_id: !input 'lightsensor_entity'
    below: !input 'illuminace_level'

  - condition: time
    after: !input 'schedule_start'
    before: !input 'schedule_stop'

action:
- service: homeassistant.turn_on
  entity_id: !input 'target_entity'
- wait_for_trigger:
    platform: state
    entity_id: !input 'motion_entity'
    to: 'off'
    for: !input 'idle_time'
- service: homeassistant.turn_off
  entity_id: !input 'target_entity'
