esphome:
  name: esp-ble-temp

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "e84dbfb7a533e1eb2b5aa2c4f37e15d5"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP-BLE-TEMP Fallback Hotspot"
    password: "WXtF9QwWdZJS"

captive_portal:

esp32_ble_tracker:

sensor:
  - platform: pvvx_mithermometer # LYWSD03MMC Mijia Therometer
    mac_address: "A1:B1:C1:D1:E1:F1" # LYWSD03MMC MAC address
    temperature:
      name: "T1 Temperature"
    humidity:
      name: "T1 Humidity"
    battery_level:
      name: "T1 Thermometer Battery Level"
    battery_voltage:
      name: "T1 Thermometer Battery Volts"


# Auto daily reset
time:
  - platform: homeassistant
    on_time:
      - seconds: 0
        minutes: 0
        hours: 4
        days_of_week: MON-SUN
        then:
           - switch.toggle: restart_switch
switch:
  - platform: restart
    name: "ESP-BLE-TEMP restart"
    id: restart_switch