esphome:
  name: esp-ble-motion

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "e84dbfb7a533e1eb2b5aa2c4f37e15d5"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP-BLE-MOTION Fallback Hotspot"
    password: "WXtF9QwWdZJS"

captive_portal:

esp32_ble_tracker:

binary_sensor:
  - platform: xiaomi_cgpr1
    name: "M1 Motion detector" # CGPR1 Motion & Light Sensor
    mac_address: A1:B1:C1:D1:E1:F1 # Device MAC address
    bindkey:  "5f60b65c144f3c6b8fdae819fca6f614"
    idle_time:
      name: "M1 Idle Time"
    battery_level:
      name: "M1 Battery Level"
    illuminance:
      name: "M1 Illuminance"

# Auto daily reset
time:
  - platform: homeassistant
    on_time:
      - seconds: 0
        minutes: 0
        hours: 4
        days_of_week: MON-SUN
        then:
           - switch.toggle: restart_switch
switch:
  - platform: restart
    name: "ESP-BLE-MOTION restart"
    id: restart_switch